export default [
  {
    id: 1,
    type: "mats",
    name: "Aeromat Elite Workout Mat with Eyelets",
    slug: "Aeromat-Elite-Workout-Mat-with-Eyelets",
    price: 25.99,
    previousPrice: 65.99,
    aviable: 10,
    featured: false,
    details: [],
    description:
      "OVERVIEV Key Features of the Aeromat Elite Workout Mat with Eyelets: Great for any floor exercis Easy to clean with damp cloth Light weight, easy to roll up, with convenient carry handle",
    pics: [
      "https://smhttp-ssl-18062.nexcesscdn.net/media/prod.image/m/a/mat.jpg",
      "https://smhttp-ssl-18062.nexcesscdn.net/media/prod.image/a/e/aero-r58-2372-blk_2_1.jpg",
    ],
    specification: "",
  },
  {
    id: 2,
    type: "mats",
    name: "Aeromat Black Rollup",
    slug: "Aeromat-Black-Rollup",
    price: 33.99,
    previousPrice: 45.99,
    aviable: 10,
    featured: false,
    description:
      "The Aeromat Rollup Mat in black is ideal for any floor exercise. Designed with closed cell foam structure, this mat has superior cushioning and is body heat retentive. The non-absorbent surface makes it impervious to sweat and water. Velcro straps are included for easy transportation. Wipe clean with a damp cloth.",
    details: [
      "Ideal for any floor exercise",
      "Designed with closed cell foam structure for superior cushioning",
      "Body heat retentive",
      "Non-absorbent surface is impervious to sweat and water",
      "Velcro straps are included for easy transportation",
      "Wipe clean with a damp cloth",
      "Dimensions: 72” L 24” W .0375” H",
    ],
    pics: [
      "https://smhttp-ssl-18062.nexcesscdn.net/media/prod.image/a/e/aeromat-blk-1_2.jpg",
    ],
    specification: "",
  },
  {
    id: 3,
    type: "mats",
    name: "Prism Self-Guided Essential Storage Package",
    slug: "Prism-Self-Guided-Essential-Storage-Package",
    price: 1025.88,
    previousPrice: 899.99,
    aviable: 5,
    featured: false,
    description:
      "This space saving storage display allows for easy access to the essential fitness training products.",
    details: [
      "16mm Exercise Mat",
      "Foam Roller",
      "4lb, 6lb, 8lb, and 10lb Medicine Balls",
      "Non-absorbent surface is impervious to sweat and water55cm and 65cm Stability Balls",
      "20lb and 30lb Resistance Cables",
      "Quick Flip Handles",
      "Mini Storage Tower",
    ],
    pics: [
      "https://smhttp-ssl-18062.nexcesscdn.net/media/prod.image/p/r/prism-deluxe-tower.jpg",
    ],
    specification: [
      ["PRODUCT NUMBER", "400 - 150 - 132"],
      ["DEMENSIONS", "64 W x 30 D x 66 H"],
      ["MANUFACTURER", "Prism Fitness Group"],
    ],
  },
  {
    id: 4,
    type: "mats",
    name: "Aeromat Blue",
    slug: "Aeromat-Blue",
    price: 55.88,
    previousPrice: 109.99,
    aviable: 5,
    featured: false,
    description:
      "Effortlessly switch between standing and floor exercises with the medium thickness of this premium exercise mat. This mat gives you the perfect surface for Pilates, yoga and a variety of other fitness types. Depending on your preference and each movement, you can switch sides between the textured one and the smooth one of this dual-sided mat.",
    details: [
      "Various Activities: use this mat to practice Pilates, yoga and a range of other fitness activities",
      "Balanced Thickness: the 5/8” thickness is soft yet firm to create the right surface for all sorts of exercises, from standing exercises to seated and lying-down exercises",
      "h3 Material: the PVC material has a closed-cell foam structure that gives it strength and cushioning; it is phthalates-free to fit your healthy values",
      "Non-absorbent surface is impervious to sweat and water55cm and 65cm Stability Balls",
      "Simple Care: water or sweat won’t soak into the mat and you can easily clean the surface with a damp cloth",
      "Quick Flip Handles",
      "Blue Color: enjoy the relaxing and vibrant shade of blue this mat comes in",
    ],
    pics: [
      "https://smhttp-ssl-18062.nexcesscdn.net/media/prod.image/a/e/aero-r58-2372-blu_2.jpg",
    ],
    specification: [["MANUFACTURER", "Aeromats"]],
  },
];
